export const dates = [
  {
    id: 1,
    code: "PS27619",
    firstName: "Hiếu",
    lastName: "Nguyễn Trung",
    email: "hieuntps27619@fpt.edu.vn",
    gender: true,
    birthday: "1991-05-24",
    phone: "0935186303",
    address: "Thành phố Hà Nội - Tỉnh Hà Nội",
    description: "Nguyễn Trung Hiếu - Thành phố Hà Nội - Tỉnh Hà Nội",
    avatar: "student1.png",
    course: "18.3",
    majorId: 1,
    semester: "Fall",
    year: 2022,
    educationProgramId: 2,
  },
  {
    id: 2,
    code: "PS27456",
    firstName: "Phát",
    lastName: "Liêu Vinh",
    email: "phatlvps27456@fpt.edu.vn",
    gender: true,
    birthday: "1999-07-16",
    phone: "09890123123",
    address: "Thành phố Hồ CHí Minh - Tỉnh Sài Gòn",
    description: "Liêu Vinh Phát - Thành phố Hồ CHí Minh - Tỉnh Sài Gòn",
    avatar: "student1.png",
    course: "18.1",
    majorId: 1,
    semester: "Fall",
    year: 2022,
    educationProgramId: 2,
  },
  {
    id: 3,
    code: "PS27619",
    firstName: "Hiếu",
    lastName: "Nguyễn Trung",
    email: "hieuntps27619@fpt.edu.vn",
    gender: true,
    birthday: "1991-05-24",
    phone: "0935186303",
    address: "Thành phố Hà Nội - Tỉnh Hà Nội",
    description: "Nguyễn Trung Hiếu - Thành phố Hà Nội - Tỉnh Hà Nội",
    avatar: "student1.png",
    course: "18.3",
    majorId: 1,
    semester: "Fall",
    year: 2022,
    educationProgramId: 2,
  },
  {
    id: 4,
    code: "PS27456",
    firstName: "Phát",
    lastName: "Liêu Vinh",
    email: "phatlvps27456@fpt.edu.vn",
    gender: true,
    birthday: "1999-07-16",
    phone: "09890123123",
    address: "Thành phố Hồ CHí Minh - Tỉnh Sài Gòn",
    description: "Liêu Vinh Phát - Thành phố Hồ CHí Minh - Tỉnh Sài Gòn",
    avatar: "student1.png",
    course: "18.1",
    majorId: 1,
    semester: "Fall",
    year: 2022,
    educationProgramId: 2,
  },
  {
    id: 5,
    code: "PS27619",
    firstName: "Hiếu",
    lastName: "Nguyễn Trung",
    email: "hieuntps27619@fpt.edu.vn",
    gender: true,
    birthday: "1991-05-24",
    phone: "0935186303",
    address: "Thành phố Hà Nội - Tỉnh Hà Nội",
    description: "Nguyễn Trung Hiếu - Thành phố Hà Nội - Tỉnh Hà Nội",
    avatar: "student1.png",
    course: "18.3",
    majorId: 1,
    semester: "Fall",
    year: 2022,
    educationProgramId: 2,
  },
  {
    id: 6,
    code: "PS27456",
    firstName: "Phát",
    lastName: "Liêu Vinh",
    email: "phatlvps27456@fpt.edu.vn",
    gender: true,
    birthday: "1999-07-16",
    phone: "09890123123",
    address: "Thành phố Hồ CHí Minh - Tỉnh Sài Gòn",
    description: "Liêu Vinh Phát - Thành phố Hồ CHí Minh - Tỉnh Sài Gòn",
    avatar: "student1.png",
    course: "18.1",
    majorId: 1,
    semester: "Fall",
    year: 2022,
    educationProgramId: 2,
  },
  {
    id: 7,
    code: "PS27619",
    firstName: "Hiếu",
    lastName: "Nguyễn Trung",
    email: "hieuntps27619@fpt.edu.vn",
    gender: true,
    birthday: "1991-05-24",
    phone: "0935186303",
    address: "Thành phố Hà Nội - Tỉnh Hà Nội",
    description: "Nguyễn Trung Hiếu - Thành phố Hà Nội - Tỉnh Hà Nội",
    avatar: "student1.png",
    course: "18.3",
    majorId: 1,
    semester: "Fall",
    year: 2022,
    educationProgramId: 2,
  },
  {
    id: 8,
    code: "PS27456",
    firstName: "Phát",
    lastName: "Liêu Vinh",
    email: "phatlvps27456@fpt.edu.vn",
    gender: true,
    birthday: "1999-07-16",
    phone: "09890123123",
    address: "Thành phố Hồ CHí Minh - Tỉnh Sài Gòn",
    description: "Liêu Vinh Phát - Thành phố Hồ CHí Minh - Tỉnh Sài Gòn",
    avatar: "student1.png",
    course: "18.1",
    majorId: 1,
    semester: "Fall",
    year: 2022,
    educationProgramId: 2,
  },
  {
    id: 9,
    code: "PS27619",
    firstName: "Hiếu",
    lastName: "Nguyễn Trung",
    email: "hieuntps27619@fpt.edu.vn",
    gender: true,
    birthday: "1991-05-24",
    phone: "0935186303",
    address: "Thành phố Hà Nội - Tỉnh Hà Nội",
    description: "Nguyễn Trung Hiếu - Thành phố Hà Nội - Tỉnh Hà Nội",
    avatar: "student1.png",
    course: "18.3",
    majorId: 1,
    semester: "Fall",
    year: 2022,
    educationProgramId: 2,
  },
  {
    id: 10,
    code: "PS27456",
    firstName: "Phát",
    lastName: "Liêu Vinh",
    email: "phatlvps27456@fpt.edu.vn",
    gender: true,
    birthday: "1999-07-16",
    phone: "09890123123",
    address: "Thành phố Hồ CHí Minh - Tỉnh Sài Gòn",
    description: "Liêu Vinh Phát - Thành phố Hồ CHí Minh - Tỉnh Sài Gòn",
    avatar: "student1.png",
    course: "18.1",
    majorId: 1,
    semester: "Fall",
    year: 2022,
    educationProgramId: 2,
  },
  {
    id: 11,
    code: "PS27619",
    firstName: "Hiếu",
    lastName: "Nguyễn Trung",
    email: "hieuntps27619@fpt.edu.vn",
    gender: true,
    birthday: "1991-05-24",
    phone: "0935186303",
    address: "Thành phố Hà Nội - Tỉnh Hà Nội",
    description: "Nguyễn Trung Hiếu - Thành phố Hà Nội - Tỉnh Hà Nội",
    avatar: "student1.png",
    course: "18.3",
    majorId: 1,
    semester: "Fall",
    year: 2022,
    educationProgramId: 2,
  },
  {
    id: 12,
    code: "PS27456",
    firstName: "Phát",
    lastName: "Liêu Vinh",
    email: "phatlvps27456@fpt.edu.vn",
    gender: true,
    birthday: "1999-07-16",
    phone: "09890123123",
    address: "Thành phố Hồ CHí Minh - Tỉnh Sài Gòn",
    description: "Liêu Vinh Phát - Thành phố Hồ CHí Minh - Tỉnh Sài Gòn",
    avatar: "student1.png",
    course: "18.1",
    majorId: 1,
    semester: "Fall",
    year: 2022,
    educationProgramId: 2,
  },
];
